pipeline:
  name: artifactory-exporter
  identifier: artifactoryexporter
  projectIdentifier: infactengops
  orgIdentifier: infactorg
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: artifactoryexporter
        build: <+input>
  stages:
    - stage:
        name: Artifactory-CI
        identifier: ArtifactoryCI
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build Artifactory Exporter Image
                  identifier: Build_Artifactory_Exporter_Image
                  spec:
                    connectorRef: artctdockerdev
                    repo: infacloud-ct-docker-dev.jfrog.io/artifactory-exporter
                    tags:
                      - latest
                    dockerfile: Dockerfile
                    context: /harness
                    resources:
                      limits:
                        memory: 2Gi
                        cpu: "2"
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: spin2preprodharnessocp
              namespace: harness-ocp-delegate
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        when:
          pipelineStatus: Success
          condition: "false"
    - stage:
        name: Artifactory-CD
        identifier: ArtifactoryCD
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: artifactory
          environment:
            environmentRef: qa_staging
            deployToAll: false
            infrastructureDefinitions:
              - identifier: testopa
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
                    delegateSelectors:
                      - ichsnp-useast1-kube-controlplane-delegate
                  failureStrategies: []
              - step:
                  type: K8sApply
                  name: Apply K8s Manifests
                  identifier: Apply_1
                  spec:
                    filePaths:
                      - helm/deployment.yaml
                      - helm/dockerImagePullSecret.yaml
                      - helm/service.yaml
                      - helm/servicemonitor.yaml
                      - helm/secret.yaml
                    skipDryRun: false
                    skipSteadyStateCheck: false
                    skipRendering: false
                    overrides:
                      - manifest:
                          identifier: Override
                          type: Values
                          spec:
                            store:
                              type: Inline
                              spec:
                                content: |-
                                  arti_uri:<+pipeline.stages.Artifactory-CD.variables.ARTI_SCRAPE_URI>
                                  arti_access_token:<+pipeline.stages.Artifactory-CD.variables.ARTI_ACCESS_TOKEN>
                  timeout: 10m
                  failureStrategies: []
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        variables:
          - name: ARTI_SCRAPE_URI
            type: String
            description: ""
            value: https://infacloud.jfrog.io/artifactory
          - name: ARTI_ACCESS_TOKEN
            type: Secret
            description: ""
            value: ARTI_ACCESS_TOKEN
        when:
          pipelineStatus: Success
