pipeline:
  name: artifactory-exporter
  identifier: artifactoryexporter
  projectIdentifier: infactengops
  orgIdentifier: infactorg
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: artifactoryexporter
        build: <+input>
  stages:
    - stage:
        name: Artifactory-CI
        identifier: ArtifactoryCI
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: artctdocker
                    image: harness:latest
                    shell: Sh
                    command: echo "hi"
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: spin2preprodharnessocp
              namespace: harness-delegate
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
    - stage:
        name: Artifactory-CD
        identifier: ArtifactoryCD
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: artifactory
          environment:
            environmentRef: qa_staging
            deployToAll: false
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
