apiVersion: v1
data:
  arti_uri: "<+serviceVariables.ARTI_ACCESS_TOKEN>"
  arti_access_token: "<+serviceVariables.ARTI_SCRAPE_URI>"
kind: Secret
metadata:
  name: artifactory-exporter-secret
type: Opaque
