apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name:  artifactory-operator-sm
  labels:
    release: monitoringaddon
    app.kubernetes.io/name: artifactory-operator
spec:
  jobLabel: app
  selector:
    matchLabels:
      app.kubernetes.io/name: artifactory-operator
  endpoints:
  - targetPort: 9531
    path: /metrics
    interval: 120
